# Generated by Django 4.0.3 on 2022-06-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tut', '0002_alter_album_id_alter_musician_id_alter_person_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='id',
            new_name='pK',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='id',
            new_name='pK',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='id',
            new_name='pK',
        ),
    ]
