# Generated by Django 4.0.3 on 2022-06-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tut', '0005_alter_album_artist_alter_album_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='persons first name'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='persons last name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='persons first name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='persons last name'),
        ),
    ]
