# Generated by Django 4.0.3 on 2022-06-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tut', '0006_alter_musician_first_name_alter_musician_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name']},
        ),
    ]
